# Generated by Django 2.1.4 on 2018-12-13 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flickrClient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchkeyword',
            name='search_count',
        ),
        migrations.AddField(
            model_name='searchkeyword',
            name='search_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date searched'),
            preserve_default=False,
        ),
    ]
